const data = {
    products: [
        {
            name: 'Rambutan',
            slug: 'fruit-Rambutan',
            category: 'Fruit',
            image: '/images/fruit1.jpg',
            price: 5,
            countryOfOrigin: 'Thailand',
            stockCount: 200,
            description: 'Rambutan is a medium-sized tropical tree in the family Sapindaceae. The name also refers to the edible fruit produced by this tree. The rambutan is native to Southeast Asia. It is closely related to several other edible tropical fruits including the lychee, longan, pulasan and guinep',
        },
        {
            name: 'Mangosteen',
            slug: 'fruit-Mangosteen',
            category: 'Fruit',
            image: '/images/fruit2.jpg',
            price: 5,
            countryOfOrigin: 'Thailand',
            stockCount: 200,
            description: 'Mangosteen, also known as the purple mangosteen, is a tropical evergreen tree with edible fruit native to tropical lands surrounding the Indian Ocean. Its origin is uncertain due to widespread prehistoric cultivation.',
        },
        {
            name: 'Mangos',
            slug: 'fruit-Mangos',
            category: 'Fruit',
            image: '/images/fruit3.jpg',
            price: 5,
            countryOfOrigin: 'Pakistan',
            stockCount: 200,
            description: 'A mango is an edible stone fruit produced by the tropical tree Mangifera indica. It is believed to have originated in the region between northwestern Myanmar, Bangladesh, and northeastern India.',
        },
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular shirt',
            isFeatured: true,
            banner: '/images/banner1.jpg',
          },
          {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 80,
            brand: 'Adidas',
            rating: 3.2,
            numReviews: 10,
            countInStock: 20,
            description: 'A popular shirt',
            isFeatured: true,
            banner: '/images/banner2.jpg',
          },
          {
            name: 'Slim Shirt',
            slug: 'slim-shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 90,
            brand: 'Raymond',
            rating: 4.5,
            numReviews: 3,
            countInStock: 20,
            description: 'A popular shirt',
          },
          {
            name: 'Golf Pants',
            slug: 'golf-pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 90,
            brand: 'Oliver',
            rating: 2.9,
            numReviews: 13,
            countInStock: 20,
            description: 'Smart looking pants',
          },
          {
            name: 'Fit Pants',
            slug: 'fit-pants',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 95,
            brand: 'Zara',
            rating: 3.5,
            numReviews: 7,
            countInStock: 20,
            description: 'A popular pants',
          },
          {
            name: 'Classic Pants',
            slug: 'classic-pants',
            category: 'Pants',
            image: '/images/pants3.jpg',
            price: 75,
            brand: 'Casely',
            rating: 2.4,
            numReviews: 14,
            countInStock: 20,
            description: 'A popular pants',
          },
    ],
};

export default data;
